spring:
  mustache:
    suffix: .mustache
    prefix: classpath:/templates/
    charset: UTF-8
    servlet:
      cache: false

server:
  port: 8080

logging:
  level:
     org.springframework.web: DEBUG

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}


tenco:
  key: ${TENCO_KEY}